version: "3"

services:

  express-app:
    image: express-js
    container_name: express-app
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: football

  next-web:
    image: next-js
    container_name: next-web
    ports:
      -  "8800:8800"
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - express-app

  py-app:
    image: kasmweb-pyapp:firefox
    container_name: kasm-pyapp
    ports:
      - "8000:6901"
    build:
      context: ./webscraper
      dockerfile: Dockerfile
    environment:
      - VNC_PW=[:pZ/_f5<hX[cH(/vc+%
    depends_on:
      - mysql

volumes:
  mysql-db: