version: "3"

services:

  express-app:
    build:
      context: ./backend
      args:
        NODE_ENV: development
    volumes:
      - ./backend:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=football
    command: npm run dev

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: football

  next-web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./client:/web
      - /web/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  py-app:
    build:
      context: ./webscraper
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./webscraper:/pyapp
    environment:
      - NODE_ENV=development