version: "3"

services:

  express-app:
    build:
      context: ./backend
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js

  next-web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start

  py-app:
    build:
      context: ./webscraper
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production