server {
    listen 80;
    listen [::]:80;

    server_name gavinkondrath.com www.gavinkondrath.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://gavinkondrath.com$request_uri;
    }
}

server {
    listen 443 default_server ssl;
    listen [::]:443 ssl;

    server_name gavinkondrath.com www.gavinkondrath.com;

    ssl_certificate /etc/nginx/ssl/live/gavinkondrath.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/gavinkondrath.com/privkey.pem; 

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://next:3000;
        proxy_redirect off;
    }
}
