server {
    listen 80;
    listen [::]:80;

    set $server_url gavinkondrath.com;
    server_name gavinkondrath.com www.gavinkondrath.com;
    #server_tokens off;

    include /etc/nginx/snippets/resolver.conf;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /ping {
        access_log off;
        add_header 'Content-Type' 'text/plain';
        return 200 "pong";
    }

    location / {
        include /etc/nginx/snippets/proxy.conf;
        include /etc/nginx/snippets/resolver.conf;

        set $upstream_app next;
        set $upstream_port 3000;
        set $upstream_proto http;
        set $upstream_keepalive false;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}

