server {
    listen 80;
    server_name dozzle.gavinkondrath.com;

    include /etc/nginx/snippets/resolver.conf;

    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name dozzle.*;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/authelia-location.conf;

    set $upstream_app dozzle;
    set $upstream_port 9999;
    set $upstream_proto http;

    location / {
        include /etc/nginx/snippets/resolver.conf;
        include /etc/nginx/snippets/proxy.conf;
        include /etc/nginx/snippets/authelia-authrequest.conf;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
