global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert_rules.yml
    #  - alert.rules_nodes
    #  - alert.rules_tasks
    #  - alert.rules_service-groups

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: node-exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter:9100

- job_name: 'prometheus'
  static_configs:
  - targets: ['host.docker.internal:9090']
  basic_auth:
      username: 'gavin'
      password: 'EvN&XhFs$Xvg9jaFjn%@JXxKg&JFuM~F'

# make sure /etc/docker/daemon.json contains:
# "metrics-addr" : "127.0.0.1:9323"
- job_name: 'docker'
  static_configs:
  - targets: ['host.docker.internal:9323']
