FROM node:16-alpine AS deps

ENV NODE_ENV=production

RUN apk add --no-cache libc6-compat

WORKDIR /web

COPY package.json yarn.lock ./
RUN yarn install

# Build the app
FROM node:16-alpine AS builder

ENV NODE_ENV=production

WORKDIR /web

COPY next.config.js ./
COPY package.json yarn.lock ./
COPY --from=deps /web/node_modules ./node_modules
COPY . ./

RUN yarn build

# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /web

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /web/public ./public

COPY --from=builder --chown=nextjs:nodejs /web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /web/.next/static ./.next/static

USER nextjs

CMD ["node", "server.js"]