FROM node:18-alpine AS base
# 16-alpine

#Next:13.4.12 works

ENV LANG=C.UTF-8


FROM base AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /web

COPY --link package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

RUN \
  if [ -f yarn.lock ]; then yarn --network-timeout 100000; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder

WORKDIR /web

COPY --from=deps /web/node_modules ./node_modules

COPY . .

COPY ./next.config.js next.config.js

# Using buildx Google Inter font will fail unless on VPN

RUN yarn build


FROM base AS runner

WORKDIR /web

ENV NODE_ENV=production

RUN : \
&& adduser --system --uid 1001 nextjs \
&& addgroup --system --gid 1001 nodejs \
&& :

COPY --from=builder /web/public ./public

RUN : \
&& mkdir .next \
&& chown nextjs:nodejs .next \
&& :

COPY --from=builder /web/next.config.js next.config.js

COPY --from=builder --chown=nextjs:node /web/.next/standalone ./

COPY --from=builder --chown=nextjs:node /web/.next/static ./.next/static

RUN : \
&& apk add --no-cache curl \
&& rm -f /sbin/apk \
&& rm -rf /etc/apk \
&& rm -rf /lib/apk \
&& rm -rf /usr/share/apk \
&& rm -rf /var/lib/apk \
&& :

USER nextjs

EXPOSE 3000

#ENV HOSTNAME "0.0.0.0"
CMD ["node", "server.js"]
