FROM node:current-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /web

COPY --link package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --network-timeout 100000; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder

WORKDIR /web
COPY --from=deps --link /web/node_modules ./node_modules
COPY --link . .
COPY ./next.config.js next.config.js
RUN yarn build

FROM base AS runner
WORKDIR /web

ENV NODE_ENV=production

RUN \
  addgroup -g 1001 -S nodejs; \
  adduser -S nextjs -u 1001

COPY --from=builder --link /web/public ./public
COPY --from=builder --link /web/next.config.js next.config.js
COPY --from=builder --link --chown=1001:1001 /web/.next/standalone ./
COPY --from=builder --link --chown=1001:1001 /web/.next/static ./.next/static

USER nextjs

CMD ["node", "server.js"]
