upstream mysql_db {
    server mysql:3306;
}

server {
    listen 3306;
    proxy_pass mysql_db;
    proxy_connect_timeout 1s;
}

upstream redis_db {
    server redis:6379;
}

server {
    listen 6379;
    proxy_pass redis_db;
    proxy_connect_timeout 1s;
}
